
version: "3.1"

services:
  web:
    container_name: mequidonalds-api
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
     - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}